options:
  modification_type: "RNA"
  organism: 9606 # NCBI taxid
  assembly: "GRCh38"
  annotation_source: null
  annotation_version: null
  sequencing_platform: "Illumina NovaSeq 6000"
  basecalling: null
  bioinformatics_workflow: "https://github.com/y9c/m6A-sacseq"
  experiment: "2-50 ng of poly-A enriched or ribosome RNA-depleted RNAs were fragmented and ligated, then divided in a 2:1 ratio. 2/3 of the starting materials are labeled by MjDim1, while the remaining 1/3 serve as the untreated control. After reverse transcription with HIV reverse transcriptase (Worthington Biochemical Corp), the cyclic allyl m6A sites are converted to mismatches, while unconverted m6A sites in the control group are read as A."
  methods: "m6A-SAC-seq"
  references:
    pubmed_id: "36434097"
    geo_accession: "GSE198246"

modifications_file: "example_files/mod_indices.csv"