options:
  modification_type: RNA          # required, always RNA in bedRMod format
  organism: 9606                  # required, NCBI taxid
  assembly: GRCh38                # required, genome/transcriptome assembly note
  annotation_source: Ensemble     # required
  annotation_version: 93          # required
  sequencing_platform: Illumina NovaSeq 6000
  basecalling: ''
  bioinformatics_workflow:
    workflow: https://github.com/anmabu/bedRMod
    coverage_function: round(coverage)
    frequency_function: round(frequency)
    score_function: round(-log10(score))
  experiment: https://doi.org/test
  external_source: GEO;GSETEST
  methods: TEST
  references:
    pubmed_id: '12345678'
  conversion_information: rgb value in df is ignored and calculated directly
